version: '3.9'

x-common-variables: &commonEnvironment
  SN_SERVER: ${SN_SERVER}
  SN_USER: ${SN_USER}
  SN_PASSWORD: ${SN_PASSWORD}
  SN_DATABASE: ${SN_DATABASE}
  SN_WAREHOUSE: ${SN_WAREHOUSE}
  SN_ROLE: ${SN_ROLE}
  APP_HOST: "0.0.0.0"

services:
  dozer-build:
    container_name: snowflake-dozer-build
    image: public.ecr.aws/getdozer/dozer-features:latest
    environment: *commonEnvironment
    working_dir: /usr/local/bin
    volumes:
      - ./dozer-config.yaml:/usr/local/bin/dozer-config.yaml
      - ./.dozer:/usr/local/bin/.dozer
    command:
      - /bin/sh
      - -c
      - dozer build

  dozer-app:
    container_name: snowflake-dozer-app
    image: public.ecr.aws/getdozer/dozer-features:latest
    environment: *commonEnvironment
    ports:
      # Internal gRPC talks to api
      - "50053:50053"
    working_dir: /usr/local/bin
    volumes:
      - ./dozer-config.yaml:/usr/local/bin/dozer-config.yaml
      - ./.dozer:/usr/local/bin/.dozer
    command:
      - /bin/sh
      - -c
      - dozer run app
    depends_on:
      dozer-build:
        condition: service_completed_successfully
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "0.0.0.0:50053", "--http2-prior-knowledge"]
      interval: 1s
      timeout: 20s
      retries: 90

  dozer-api:
    container_name: snowflake-dozer-api
    links:
      - dozer-app
    image: public.ecr.aws/getdozer/dozer-features:latest
    environment:
      <<: *commonEnvironment
      APP_HOST: 'dozer-app'
    ports:
      # REST APIs are published on port 8080
      - "8080:8080"
      # gRPC are available over 50051
      - "50051:50051"
    depends_on:
      dozer-app:
        condition: service_healthy
    working_dir: /usr/local/bin
    volumes:
      - ./dozer-config.yaml:/usr/local/bin/dozer-config.yaml
      - ./.dozer:/usr/local/bin//.dozer
    command:
      - /bin/sh
      - -c
      - dozer run api
    stdin_open: true
    tty: true
